# Copyright 2023 OpenSynergy Indonesia
# Copyright 2023 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
# pylint: disable=C8101
{
    "name": "Letter Management",
    "version": "14.0.1.8.3",
    "contributors": ["Andhitia Rama <andhitia.r@gmail.com>"],
    "website": "https://simetri-sinergi.id",
    "author": "PT. Simetri Sinergi Indonesia, OpenSynergy Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "depends": [
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_partner_mixin",
        "web_tour",
    ],
    "data": [
        "security/ir_module_category/ir_module_category.xml",
        "security/ir_module_category/outgoing_letter.xml",
        "security/ir_module_category/incoming_letter.xml",
        "security/ir_module_category/internal_memo.xml",
        "security/res_groups/letter_type.xml",
        "security/res_groups/internal_memo_type.xml",
        "security/res_groups/outgoing_letter.xml",
        "security/res_groups/incoming_letter.xml",
        "security/res_groups/internal_memo.xml",
        "security/ir_model_access/letter_type.xml",
        "security/ir_model_access/internal_memo_type.xml",
        "security/ir_model_access/outgoing_letter.xml",
        "security/ir_model_access/incoming_letter.xml",
        "security/ir_model_access/internal_memo.xml",
        "security/ir_rule/incoming_letter.xml",
        "security/ir_rule/outgoing_letter.xml",
        "security/ir_rule/internal_memo.xml",
        "ir_sequence/outgoing_letter.xml",
        "ir_sequence/incoming_letter.xml",
        "ir_sequence/internal_memo.xml",
        "sequence_template/outgoing_letter.xml",
        "sequence_template/incoming_letter.xml",
        "sequence_template/internal_memo.xml",
        "approval_template/outgoing_letter.xml",
        "approval_template/incoming_letter.xml",
        "approval_template/internal_memo.xml",
        "policy_template/outgoing_letter.xml",
        "policy_template/incoming_letter.xml",
        "policy_template/internal_memo.xml",
        "menu.xml",
        "views/letter_type_views.xml",
        "views/internal_memo_type.xml",
        "views/letter_mixin_views.xml",
        "views/outgoing_letter_views.xml",
        "views/incoming_letter_views.xml",
        "views/internal_memo.xml",
        "views/assets.xml",
    ],
    "images": [],
}
